### ISSUE TITLE
compatibility with R at the end of dada2 pipeline

### ISSUE THREAD

**Issue by callmcgovern** [yphsieh/16S-ITGDB#2]
Hello, 
I just processed my 16s data with the dada2 pipeline and I am at the Assign Taxonomy step. I was trying to use the ITGDB database to assign taxonomy but I am getting errors that the file is not in the correct file format for the assignTaxonomy function. 
Do you know if I can make this work in R studio using this function? 
Thank you!

**Comment by cil6758** [comment]
Hi, callmcgovern:
      Sorry for the late reply and thanks for raising this issue. 16S-ITGDB also supports DADA2 function in QIIME2 pipeline. So, 16S-ITGDB could also work with DADA2 package in R language, just like QIIME2.

Best regards

**Comment by callmcgovern** [comment]
Thank you @cil6758 . I figured it out and it worked :)
